version: '2'

services:


  app-core:
    image: cuba-ordermanagement-app-core:latest
    environment:
      - CUBA_CLUSTER_ENABLED=false
      - CUBA_WEB_PORT=8080
      - CUBA_WEB_HOST_NAME=localhost
      - CUBA_DB_HOST=postgres
      - CUBA_DB_PORT=5432
      - CUBA_DB_USERNAME=postgres
      - CUBA_DB_PASSWORD=postgres
      - CUBA_DB_NAME=postgres
    networks:
      - cuba-network


  app:
    image: cuba-ordermanagement-app:latest
    ports:
     - "8080:8080"
    environment:
     - CUBA_CORE_URL_CONNECTION_LIST=http://app-core:8080
     - CUBA_WEB_PORT=8080
     - CUBA_WEB_HOST_NAME=192.168.99.100
    networks:
      - cuba-network

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - cuba-network

networks:
  cuba-network:
